# Generated by Django 4.1.3 on 2022-11-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('fullscore', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=15)),
                ('group', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=125)),
                ('credit', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdid', models.CharField(default='', max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluateapp.section')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=1)),
                ('score', models.FloatField(default=0.0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluateapp.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluateapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluateapp.subject'),
        ),
    ]
